apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  annotations:
    cert-manager.io/inject-ca-from: {{ include "resource.default.namespace" . }}/{{ include "resource.default.name" . }}-certificates
  labels:
    {{- include "labels.common" . | nindent 4 }}
webhooks:
  - name: awsclusters.v1alpha2.{{ include "resource.default.name" . }}.giantswarm.io
    admissionReviewVersions: [v1]
    failurePolicy: Ignore
    sideEffects: None
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /mutate/v1alpha2/awscluster
      caBundle: Cg==
    rules:
      - apiGroups: ["infrastructure.giantswarm.io"]
        resources:
          - awsclusters
        apiVersions:
          - v1alpha2
        operations:
          - CREATE
          - UPDATE
  - name: awsmachinedeployments.v1alpha2.{{ include "resource.default.name" . }}.giantswarm.io
    admissionReviewVersions: [v1]
    failurePolicy: Ignore
    sideEffects: None
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /mutate/v1alpha2/awsmachinedeployment
      caBundle: Cg==
    rules:
      - apiGroups: ["infrastructure.giantswarm.io"]
        resources:
          - awsmachinedeployments
        apiVersions:
          - v1alpha2
        operations:
          - CREATE
          - UPDATE
  - name: awscontrolplanes.v1alpha2.{{ include "resource.default.name" . }}.giantswarm.io
    admissionReviewVersions: [v1]
    failurePolicy: Ignore
    sideEffects: NoneOnDryRun
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /mutate/v1alpha2/awscontrolplane
      caBundle: Cg==
    rules:
      - apiGroups: ["infrastructure.giantswarm.io"]
        resources:
          - "awscontrolplanes"
        apiVersions:
          - "v1alpha2"
        operations:
          - CREATE
          - UPDATE
  - name: clusters.v1alpha2.{{ include "resource.default.name" . }}.giantswarm.io
    admissionReviewVersions: [v1]
    failurePolicy: Ignore
    sideEffects: None
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /mutate/v1alpha2/cluster
      caBundle: Cg==
    rules:
      - apiGroups: ["cluster.x-k8s.io"]
        resources:
          - clusters
        apiVersions:
          - v1alpha2
        operations:
          - CREATE
          - UPDATE
  - name: g8scontrolplanes.v1alpha2.{{ include "resource.default.name" . }}.giantswarm.io
    admissionReviewVersions: [v1]
    failurePolicy: Ignore
    sideEffects: NoneOnDryRun
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /mutate/v1alpha2/g8scontrolplane
      caBundle: Cg==
    rules:
      - apiGroups: ["infrastructure.giantswarm.io"]
        resources:
          - "g8scontrolplanes"
        apiVersions:
          - "v1alpha2"
        operations:
          - CREATE
          - UPDATE
  - name: machinedeployments.v1alpha2.{{ include "resource.default.name" . }}.giantswarm.io
    admissionReviewVersions: [v1]
    failurePolicy: Ignore
    sideEffects: None
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /mutate/v1alpha2/machinedeployment
      caBundle: Cg==
    rules:
      - apiGroups: ["cluster.x-k8s.io"]
        resources:
          - machinedeployments
        apiVersions:
          - v1alpha2
        operations:
          - CREATE
          - UPDATE
  - name: awsclusters.v1alpha3.{{ include "resource.default.name" . }}.giantswarm.io
    admissionReviewVersions: [v1]
    failurePolicy: Ignore
    sideEffects: None
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /mutate/v1alpha3/awscluster
      caBundle: Cg==
    rules:
      - apiGroups: ["infrastructure.giantswarm.io"]
        resources:
          - awsclusters
        apiVersions:
          - v1alpha3
        operations:
          - CREATE
          - UPDATE
  - name: awsmachinedeployments.v1alpha3.{{ include "resource.default.name" . }}.giantswarm.io
    admissionReviewVersions: [v1]
    failurePolicy: Ignore
    sideEffects: None
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /mutate/v1alpha3/awsmachinedeployment
      caBundle: Cg==
    rules:
      - apiGroups: ["infrastructure.giantswarm.io"]
        resources:
          - awsmachinedeployments
        apiVersions:
          - v1alpha3
        operations:
          - CREATE
          - UPDATE
  - name: awscontrolplanes.v1alpha3.{{ include "resource.default.name" . }}.giantswarm.io
    admissionReviewVersions: [v1]
    failurePolicy: Ignore
    sideEffects: NoneOnDryRun
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /mutate/v1alpha3/awscontrolplane
      caBundle: Cg==
    rules:
      - apiGroups: ["infrastructure.giantswarm.io"]
        resources:
          - "awscontrolplanes"
        apiVersions:
          - "v1alpha3"
        operations:
          - CREATE
          - UPDATE
  - name: clusters.v1alpha3.{{ include "resource.default.name" . }}.giantswarm.io
    admissionReviewVersions: [v1]
    failurePolicy: Ignore
    sideEffects: None
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /mutate/v1alpha3/cluster
      caBundle: Cg==
    rules:
      - apiGroups: ["cluster.x-k8s.io"]
        resources:
          - clusters
        apiVersions:
          - v1alpha3
        operations:
          - CREATE
          - UPDATE
  - name: g8scontrolplanes.v1alpha3.{{ include "resource.default.name" . }}.giantswarm.io
    admissionReviewVersions: [v1]
    failurePolicy: Ignore
    sideEffects: NoneOnDryRun
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /mutate/v1alpha3/g8scontrolplane
      caBundle: Cg==
    rules:
      - apiGroups: ["infrastructure.giantswarm.io"]
        resources:
          - "g8scontrolplanes"
        apiVersions:
          - "v1alpha3"
        operations:
          - CREATE
          - UPDATE
  - name: machinedeployments.v1alpha3.{{ include "resource.default.name" . }}.giantswarm.io
    admissionReviewVersions: [v1]
    failurePolicy: Ignore
    sideEffects: None
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /mutate/v1alpha3/machinedeployment
      caBundle: Cg==
    rules:
      - apiGroups: ["cluster.x-k8s.io"]
        resources:
          - machinedeployments
        apiVersions:
          - v1alpha3
        operations:
          - CREATE
          - UPDATE
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  annotations:
    cert-manager.io/inject-ca-from: {{ include "resource.default.namespace" . }}/{{ include "resource.default.name" . }}-certificates
  labels:
    {{- include "labels.common" . | nindent 4 }}
webhooks:
  - name: awsclusters.v1alpha2.{{ include "resource.default.name" . }}.giantswarm.io
    admissionReviewVersions: [v1]
    failurePolicy: Ignore
    sideEffects: None
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /validate/v1alpha2/awscluster
      caBundle: Cg==
    rules:
    - apiGroups: ["infrastructure.giantswarm.io"]
      resources:
        - awsclusters
      apiVersions:
        - v1alpha2
      operations:
        - CREATE
        - UPDATE
  - name: awsmachinedeployments.v1alpha2.{{ include "resource.default.name" . }}.giantswarm.io
    admissionReviewVersions: [v1]
    failurePolicy: Ignore
    sideEffects: None
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /validate/v1alpha2/awsmachinedeployment
      caBundle: Cg==
    rules:
      - apiGroups: ["infrastructure.giantswarm.io"]
        resources:
          - awsmachinedeployments
        apiVersions:
          - v1alpha2
        operations:
          - CREATE
          - UPDATE
  - name: awscontrolplanes.v1alpha2.{{ include "resource.default.name" . }}.giantswarm.io
    admissionReviewVersions: [v1]
    failurePolicy: Ignore
    sideEffects: NoneOnDryRun
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /validate/v1alpha2/awscontrolplane
      caBundle: Cg==
    rules:
      - apiGroups: ["infrastructure.giantswarm.io"]
        resources:
          - "awscontrolplanes"
        apiVersions:
          - "v1alpha2"
        operations:
          - CREATE
          - UPDATE
  - name: clusters.v1alpha2.{{ include "resource.default.name" . }}.giantswarm.io
    admissionReviewVersions: [v1]
    failurePolicy: Ignore
    sideEffects: None
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /validate/v1alpha2/cluster
      caBundle: Cg==
    rules:
      - apiGroups: ["cluster.x-k8s.io"]
        resources:
          - clusters
        apiVersions:
          - v1alpha2
        operations:
          - CREATE
          - UPDATE
  - name: g8scontrolplanes.v1alpha2.{{ include "resource.default.name" . }}.giantswarm.io
    admissionReviewVersions: [v1]
    failurePolicy: Ignore
    sideEffects: NoneOnDryRun
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /validate/v1alpha2/g8scontrolplane
      caBundle: Cg==
    rules:
      - apiGroups: ["infrastructure.giantswarm.io"]
        resources:
          - "g8scontrolplanes"
        apiVersions:
          - "v1alpha2"
        operations:
          - CREATE
          - UPDATE
  - name: machinedeployments.v1alpha2.{{ include "resource.default.name" . }}.giantswarm.io
    admissionReviewVersions: [v1]
    failurePolicy: Ignore
    sideEffects: None
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /validate/v1alpha2/machinedeployment
      caBundle: Cg==
    rules:
      - apiGroups: ["cluster.x-k8s.io"]
        resources:
          - machinedeployments
        apiVersions:
          - v1alpha2
        operations:
          - CREATE
          - UPDATE
  - name: networkpools.v1alpha2.{{ include "resource.default.name" . }}.giantswarm.io
    admissionReviewVersions: [v1]
    failurePolicy: Ignore
    sideEffects: NoneOnDryRun
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /validate/v1alpha2/networkpool
      caBundle: Cg==
    rules:
      - apiGroups: ["infrastructure.giantswarm.io"]
        resources:
          - "networkpools"
        apiVersions:
          - "v1alpha2"
        operations:
          - CREATE
          - UPDATE
  - name: awsclusters.v1alpha3.{{ include "resource.default.name" . }}.giantswarm.io
    admissionReviewVersions: [v1]
    failurePolicy: Ignore
    sideEffects: None
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /validate/v1alpha3/awscluster
      caBundle: Cg==
    rules:
    - apiGroups: ["infrastructure.giantswarm.io"]
      resources:
        - awsclusters
      apiVersions:
        - v1alpha3
      operations:
        - CREATE
        - UPDATE
  - name: awsmachinedeployments.v1alpha3.{{ include "resource.default.name" . }}.giantswarm.io
    admissionReviewVersions: [v1]
    failurePolicy: Ignore
    sideEffects: None
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /validate/v1alpha3/awsmachinedeployment
      caBundle: Cg==
    rules:
      - apiGroups: ["infrastructure.giantswarm.io"]
        resources:
          - awsmachinedeployments
        apiVersions:
          - v1alpha3
        operations:
          - CREATE
          - UPDATE
  - name: awscontrolplanes.v1alpha3.{{ include "resource.default.name" . }}.giantswarm.io
    admissionReviewVersions: [v1]
    failurePolicy: Ignore
    sideEffects: NoneOnDryRun
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /validate/v1alpha3/awscontrolplane
      caBundle: Cg==
    rules:
      - apiGroups: ["infrastructure.giantswarm.io"]
        resources:
          - "awscontrolplanes"
        apiVersions:
          - "v1alpha3"
        operations:
          - CREATE
          - UPDATE
  - name: clusters.v1alpha3.{{ include "resource.default.name" . }}.giantswarm.io
    admissionReviewVersions: [v1]
    failurePolicy: Ignore
    sideEffects: None
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /validate/v1alpha3/cluster
      caBundle: Cg==
    rules:
      - apiGroups: ["cluster.x-k8s.io"]
        resources:
          - clusters
        apiVersions:
          - v1alpha3
        operations:
          - CREATE
          - UPDATE
  - name: g8scontrolplanes.v1alpha3.{{ include "resource.default.name" . }}.giantswarm.io
    admissionReviewVersions: [v1]
    failurePolicy: Ignore
    sideEffects: NoneOnDryRun
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /validate/v1alpha2/g8scontrolplane
      caBundle: Cg==
    rules:
      - apiGroups: ["infrastructure.giantswarm.io"]
        resources:
          - "g8scontrolplanes"
        apiVersions:
          - "v1alpha3"
        operations:
          - CREATE
          - UPDATE
  - name: machinedeployments.v1alpha3.{{ include "resource.default.name" . }}.giantswarm.io
    admissionReviewVersions: [v1]
    failurePolicy: Ignore
    sideEffects: None
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /validate/v1alpha3/machinedeployment
      caBundle: Cg==
    rules:
      - apiGroups: ["cluster.x-k8s.io"]
        resources:
          - machinedeployments
        apiVersions:
          - v1alpha3
        operations:
          - CREATE
          - UPDATE
  - name: networkpools.v1alpha3.{{ include "resource.default.name" . }}.giantswarm.io
    admissionReviewVersions: [v1]
    failurePolicy: Ignore
    sideEffects: NoneOnDryRun
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /validate/v1alpha3/networkpool
      caBundle: Cg==
    rules:
      - apiGroups: ["infrastructure.giantswarm.io"]
        resources:
          - "networkpools"
        apiVersions:
          - "v1alpha3"
        operations:
          - CREATE
          - UPDATE