version: 2.1

orbs:
  architect: giantswarm/architect@4.0.0


workflows:
  version: 2
  build:
    jobs:
      - architect/go-build:
          name: build-aws-admission-controller
          context: architect
          binary: aws-admission-controller
          filters:
            # Do this on every commit and when a new tag is created.
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-aws-admission-controller-to-quay
          context: architect
          image: "quay.io/giantswarm/aws-admission-controller"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - build-aws-admission-controller
          # Do this on every commit and when a new tag is created.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-aws-admission-controller-to-aliyun
          context: architect
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/aws-admission-controller"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - build-aws-admission-controller
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-aws-admission-controller-to-control-plane-app-catalog
          context: architect
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "aws-admission-controller"
          requires:
            - push-aws-admission-controller-to-quay
          filters:
            # Do this on every commit and when a new tag is created.
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-aws-admission-controller-to-aws-app-collection
          context: architect
          app_name: "aws-admission-controller"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-aws-admission-controller-to-control-plane-app-catalog
          filters:
            # Only do this when a new tag is created.
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
