version: 2.1

orbs:
  architect: giantswarm/architect@4.35.6


workflows:
  version: 2
  build:
    jobs:
    - architect/go-build:
        name: build-aws-admission-controller
        context: architect
        binary: aws-admission-controller
        filters:
            # Do this on every commit and when a new tag is created.
          tags:
            only: /^v.*/

    - architect/push-to-registries:
        context: architect
        name: push-to-registries
        requires:
        - build-aws-admission-controller
        filters:
          tags:
            only: /^v.*/

          branches:
            ignore:
            - main
            - master
    - architect/push-to-app-catalog:
        name: push-aws-admission-controller-to-control-plane-app-catalog
        context: architect
        app_catalog: control-plane-catalog
        app_catalog_test: control-plane-test-catalog
        chart: aws-admission-controller
        requires:
        - push-to-registries
        filters:
            # Do this on every commit and when a new tag is created.
          tags:
            only: /^v.*/

          branches:
            ignore:
            - main
            - master
    - architect/push-to-app-collection:
        name: push-aws-admission-controller-to-aws-app-collection
        context: architect
        app_name: aws-admission-controller
        app_collection_repo: aws-app-collection
        requires:
        - push-aws-admission-controller-to-control-plane-app-catalog
        filters:
            # Only do this when a new tag is created.
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/
