aws:
  availabilityZones: []
  instance:
    allowed: []
  region: ""

managementCluster:
  kubernetes:
    auth:
      tenantAdminTargetGroup: ""
      viewAllTargetGroup: ""

workloadCluster:
  baseDomain: ""
  cni:
    cidr: ""
  docker:
    cidr: ""
  ipam:
    cidr: ""
  kubernetes:
    api:
      clusterIPRange: ""

registry:
  domain: docker.io

image:
  name: "giantswarm/aws-admission-controller"
  tag: "[[ .Version ]]"

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

deploymentStrategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  type: RollingUpdate

podDisruptionBudget:
  enabled: true
  minAvailable: 1
